### ISSUE TITLE
Metadata for the data

### ISSUE THREAD

**Issue by stefanusgusega** [Forsad/FluSense-data#1]
This repository doesn't contain metadata in CSV version. So can I make a pull request to include the metadata? Thank you!

**Comment by Forsad** [comment]
Hey, thanks! you are welcome to do that (I thought we would end up adding more data, which hasn't been done yet). Feel free to do that.

**Comment by stefanusgusega** [comment]
Okay, later I will do that. Thank you!

**Comment by stefanusgusega** [comment]
I've made my pull request. Thank you!
